[package]
name = "chip8-rust"
version = "0.1.0"
authors = ["Naman Sood <mail@nsood.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
